# Generated by Django 4.2.5 on 2023-11-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('underprogress', 'Underprogress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='assigned', max_length=13)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clientbooking')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client')),
                ('providerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.serviceprovider')),
                ('workerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.worker')),
            ],
        ),
    ]
