# Generated by Django 4.2.5 on 2024-02-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypes',
            name='number_of_providers',
            field=models.IntegerField(default=0),
        ),
    ]
