# Generated by Django 4.2.5 on 2023-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_workerreport_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
