# Generated by Django 4.2.5 on 2024-02-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_servicetypes_number_of_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.CharField(default='kottayam', max_length=100),
        ),
    ]
