# Generated by Django 4.2.5 on 2023-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_service_rating_service_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
