# Generated by Django 4.2.5 on 2024-02-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_serviceprovider_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='managerid',
        ),
    ]
