# Generated by Django 4.2.5 on 2023-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='paymentstatus',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=15),
        ),
    ]
