# Generated by Django 4.2.5 on 2024-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_branch_managerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
