# Generated by Django 4.2.5 on 2023-11-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_service_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerreport',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled'), ('reportgiven', 'ReportGiven'), ('reportverified', 'ReportVerified')], default='reportgiven', max_length=15),
        ),
    ]
