# Generated by Django 4.2.5 on 2024-02-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_branch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.branch')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.branchmanager')),
            ],
        ),
    ]
