# Generated by Django 4.2.5 on 2024-02-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_branchmanagerassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanager',
            name='providerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.serviceprovider'),
        ),
    ]
