# Generated by Django 4.2.5 on 2024-02-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_branchmanager_providerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLeaveapplication',
            fields=[
                ('leaveid', models.AutoField(primary_key=True, serialize=False)),
                ('leavetype', models.CharField(choices=[('medical', 'Medical'), ('family_emergency', 'FamilyEmergency'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_leave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
