# Generated by Django 4.2.5 on 2024-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_workerleaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='workerid',
        ),
        migrations.AddField(
            model_name='service',
            name='workerid',
            field=models.ManyToManyField(to='app1.worker'),
        ),
    ]
