# Generated by Django 4.2.5 on 2024-02-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_service_workerid_service_workerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiBranch',
            fields=[
                ('branchid', models.AutoField(primary_key=True, serialize=False)),
                ('providername', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('status', models.CharField(default='inactive', max_length=10)),
                ('providerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.serviceprovider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.servicetypes')),
            ],
        ),
    ]
