# Generated by Django 5.0.1 on 2024-03-07 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_salaryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('additional_info', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.branch')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.worker')),
            ],
        ),
    ]
