# Generated by Django 5.0.1 on 2024-03-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_clientworkrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='requested', max_length=10)),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clientworkrequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.worker')),
            ],
        ),
    ]
