# Generated by Django 5.0.1 on 2024-03-20 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonusid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reportid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workerreport')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
