# Generated by Django 5.0.1 on 2024-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
