# Generated by Django 5.0.1 on 2024-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_expense_expense_alter_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
