# Generated by Django 5.0.1 on 2024-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
